### ISSUE TITLE
Fourier basis in representation example

### ISSUE THREAD

**Issue by pablomm** [GAA-UAM/scikit-fda#108]
https://github.com/GAA-UAM/scikit-fda/blob/ee8b31604667b910e5624d997af5e10a25c78386/examples/plot_representation.py#L97-L104
I don't know if this sentence is completely correct. The functions will start and end at the same point if the period of the basis is the same than the domain range, but we can set the period to `2*|domain_range|` to avoid this problem. 
```python
period = 2 * ( fd.domain_range[0][1] - fd.domain_range[0][0])
fd_basis = fd.to_basis( 
      basis.Fourier(domain_range=fd.domain_range[0], nbasis=7, period=period)
  )
fd_basis.plot()
```
Result:
![Figure_1](https://user-images.githubusercontent.com/16774925/58013525-09b6da80-7af7-11e9-945d-94c4b81e5b38.png)

**Comment by vnmabus** [comment]
This was already changed. I will close this issue.
