### ISSUE TITLE
Retrieve coefficients for function reconstruction

### ISSUE THREAD

**Issue by SirWindfield** [GAA-UAM/scikit-fda#135]
Hey there!

I fitted a KNN FDataGrid to my input data. It actually looks pretty good so far and I now would like to "export" it so I can represent the function as numerical values (preferable in a numpy array).

I saw that you offer some basis that can be used to "export" the underlying representation. Could you elaborrate on what basis should be used when? 
My data represents a demand/supply curve. I tried the BSpline one but it only constructs something close to a sine wave which doesn't really represent my data.

Here is an image of the graph itself:
![grafik](https://user-images.githubusercontent.com/5113257/60880775-9a32b100-a244-11e9-997a-9b27d5f9acf0.png)

Is there some way to get the `raw` representation instead of transforming it to another basis?

**Comment by vnmabus** [comment]
Thank you for asking!

The `FDataGrid` object stores the values at the observation points in an internal matrix `data_matrix`. As your codomain are the real numbers, you probably will want to remove the last dimension:

```python
matrix = fd.data_matrix[..., 0]
```

You can also call the functional object as a normal function, passing a list of evaluation points:

```python
matrix = fd([0, 13, 15, 19, 21, 100])
```

In that case, extrapolation or interpolation may be required (by default, it will use linear interpolation).

If you want to know more about interpolation and extrapolation, there are examples dealing with this topic:
- [Interpolation](https://fda.readthedocs.io/en/latest/auto_examples/plot_interpolation.html)
- [Extrapolation](https://fda.readthedocs.io/en/latest/auto_examples/plot_extrapolation.html)

**Comment by SirWindfield** [comment]
Thanks for helping me out!
Is it possible to normalize different approximations of different data points to have the same number of coefficients? 
For example, I have one curve that is created using 1100 and another one using 1300 coordinate points, would it be possible to represent both using the same sized matrix/vector of coefficients?

**Comment by vnmabus** [comment]
By the way, if you want to transform your data to a functional basis, instead of working with the raw values,  then you will not have `FDataGrid` objects anymore, but `FDataBasis`. This can be done, for example using the method `to_basis` with a suitable basis:

```python
fd_basis = fd.to_basis(
    skfda.representation.basis.BSpline(domain_range=fd.domain_range[0], nbasis=7)
    )
```

A higher number of elements in the basis usually makes curves that follow more closely the data. In that case,  the coefficients can be obtained as `fd.coefficients`.

**Comment by SirWindfield** [comment]
> ```python
> fd_basis = fd.to_basis(
>     skfda.representation.basis.BSpline(domain_range=fd.domain_range[0], nbasis=7)
>     )
> ```

Which of the basis would be more appropiate for my type of data? I tried the `BSpline` one but it didn't seem to fit the data too good...

**Comment by vnmabus** [comment]
> Thanks for helping me out!
> Is it possible to normalize different approximations of different data points to have the same number of coefficients?
> For example, I have one curve that is created using 1100 and another one using 1300 coordinate points, would it be possible to represent both using the same sized matrix/vector of coefficients?

The values in the `FDataGrid` are not coefficients, but the values of the function at the discretization points. In a recent commit, I changed the API of the kernel smoothers tho become more scikit-learn-like. In the same commit I allowed outputing the result in different discretization points, with a parameter `output_points`. You can see that in the [documentation](https://fda.readthedocs.io/en/latest/modules/preprocessing/autosummary/skfda.preprocessing.smoothing.kernel_smoothers.KNeighborsSmoother.html#skfda.preprocessing.smoothing.kernel_smoothers.KNeighborsSmoother) .

**Comment by vnmabus** [comment]
> > ```python
> > fd_basis = fd.to_basis(
> >     skfda.representation.basis.BSpline(domain_range=fd.domain_range[0], nbasis=7)
> >     )
> > ```
> 
> Which of the basis would be more appropiate for my type of data? I tried the `BSpline` one but it didn't seem to fit the data too good...

First, you have to know if you want to work with data in a basis system, or you are fine using discretized data.

If you want to use a basis, `BSpline` is usually the preferred basis for non-periodic data. You should be sure to explicitly define the `domain_range` to be the same as in the original data, in order to have good results. You could also try to increase the number of elements in the basis, to approximate your data accurately.

**Comment by SirWindfield** [comment]
If I understood you correctly, BSpline would be a good fit as my data is not periodic. I experimented around a bit but noticed that using higher `nbasis` sizes (as you suggested) keeps throwing errors that I have negative elements at n-th index when trying to convert it to a BSpline.

By best approach is this one with `nbsais=8`, higher ones lead to peaks of 2500% the original data, making the original graph (the blue one) look like a linear function (because the plotting area gets zoomed out).
![grafik](https://user-images.githubusercontent.com/5113257/60887633-22b94d80-a255-11e9-95e1-c9f68fd9d353.png)

Am I doing something wrong or is it just not possible to approx my function?

**Comment by vnmabus** [comment]
It looks to me that you are doing something wrong. I tried using a function similar to yours and I could match the function almost exactly adding elements to the basis representation. Can I see the code that you are using, and the sample points of your function?

**Comment by SirWindfield** [comment]
Sure. My `sample_points` vector spans from (-500,3000), almost evenly. It's of length 753.

|index|value|
|---|---|
|    Price |  Volume|
|0|  -500.0  
|1 | -499.5  
|2|  -499.1  
|3 | -499.0  
|4 | -498.9
|5 | -498.0 
|6|  -497.9  
|7|  -490.0 
|8 | -489.9 
|9 | -455.0  
|10| -454.9  
|11| -450.0  
|12 |-428.1  

My `data` points are just y values, decreasing too. There are, however, multiple x values that map to the same y value (if that is important).

I call the method as follows:
```python
sample_points # nparray 
data # nparray
fd = FDataGrid(data, sample_points=sample_points, dataset_label='Demand', axes_labels=['price', 'demand'])

param_values = np.linspace(start=2, stop=25, num=24) # taken from documentation example
knn = val.SmoothingParameterSearch(
    ks.KNeighborsSmoother(), param_values)
knn.fit(fd)
knn_fd = knn.transform(fd)

fd.scatter(s=0.5)
knn_fd.plot()

# bspline
spline = knn_fd.to_basis(skfda.representation.basis.BSpline(domain_range=knn_fd.domain_range[0], nbasis=8))
spline.plot()

ax = plt.gca()
ax.legend(['original data', 'knn', 'b spline'])


```

**Comment by vnmabus** [comment]
> **EDIT**
> They actually aren't evenly spaced out. The larger the number gets, the less values and the larger the gaps between my sample_points get. That would probably explain why my graphs tend to escalate at the higher x values. My data density is mostly around the strong monoton part, before it flattens out.

That is what I suspected from the scatter plot. Can you try to output in the smoother evenly spaced points, using the `output_points` parameter of the `KNeighborsSmoother` object, and see if the basis representation improves?

**Comment by SirWindfield** [comment]
So I generated a linearly spaced vector with the same number of elements and same range as my sample_points but they are now evenly spaced out. I pass that vector to the `KNeighborsSmoother`. The resulting graph looks like this:
![grafik](https://user-images.githubusercontent.com/5113257/60893982-243d4280-a262-11e9-8594-fe278907acda.png)

It still (for some reason) diverges for higher x.
I couldn't use my old parameters because I walys got a `LinAlgError`. My parameters are now `order=3, nbasis=3`, any other combination that I tried didn't generate a graph.

I tried to trim the last entries of my data that are farer out than the other ones. That resulted in a quite nice approximation using `nbasis=31`. But I would rather not do that and use all data available. I have no clue what I am doing wrong :( It's basically the same data shape as you used in the "kernel estimation" example on the website.

**Comment by vnmabus** [comment]
Have you tried the following code?

```python
sample_points # nparray 
data # nparray
fd = FDataGrid(data, sample_points=sample_points, dataset_label='Demand', axes_labels=['price', 'demand'])

param_values = np.linspace(start=2, stop=25, num=24) # taken from documentation example
knn = val.SmoothingParameterSearch(
    ks.KNeighborsSmoother(output_points=np.linspace(-500, 3000, 1000)), 
    param_values)
knn.fit(fd)
knn_fd = knn.transform(fd)

fd.scatter(s=0.5)
knn_fd.plot()

# bspline
spline = knn_fd.to_basis(skfda.representation.basis.BSpline(domain_range=knn_fd.domain_range[0], nbasis=8))
spline.plot()

ax = plt.gca()
ax.legend(['original data', 'knn', 'b spline'])
```

It is basically your previous code, but using `output_points` to make the result of the smoothing evenly spaced.

**Comment by SirWindfield** [comment]
I tried the exact same thing, but I always got errors like `LinAlgError: 9-th leading minor of the array is not positive definite`. Changing `nbasis` and `order` just shifts the index that gets displayed within the error message.

<details><summary>Error message</summary>
<p>
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-146-8baf26c55b86> in <module>
      2 plt.figure(figsize=(18,9))
      3 fd.scatter(s=0.5)
----> 4 spline = knn_fd.to_basis(skfda.representation.basis.BSpline(domain_range=knn_fd.domain_range[0], nbasis=8))
      5 spline.plot()

~\AppData\Roaming\Python\Python36\site-packages\skfda\representation\grid.py in to_basis(self, basis, **kwargs)
    839                                             basis,
    840                                             keepdims=self.keepdims,
--> 841                                             **kwargs)
    842 
    843     def to_grid(self, sample_points=None):

~\AppData\Roaming\Python\Python36\site-packages\skfda\representation\basis.py in from_data(cls, data_matrix, sample_points, basis, weight_matrix, smoothness_parameter, penalty_degree, penalty_coefficients, penalty_matrix, method, keepdims)
   1725 
   1726                 coefficients = scipy.linalg.cho_solve(scipy.linalg.cho_factor(
-> 1727                     left_matrix, lower=True), right_matrix)
   1728 
   1729                 # The ith column is the coefficients of the ith basis for each

~\AppData\Roaming\Python\Python36\site-packages\scipy\linalg\decomp_cholesky.py in cho_factor(a, lower, overwrite_a, check_finite)
    153     """
    154     c, lower = _cholesky(a, lower=lower, overwrite_a=overwrite_a, clean=False,
--> 155                          check_finite=check_finite)
    156     return c, lower
    157 

~\AppData\Roaming\Python\Python36\site-packages\scipy\linalg\decomp_cholesky.py in _cholesky(a, lower, overwrite_a, clean, check_finite)
     38     if info > 0:
     39         raise LinAlgError("%d-th leading minor of the array is not positive "
---> 40                           "definite" % info)
     41     if info < 0:
     42         raise ValueError('LAPACK reported an illegal value in {}-th argument'

LinAlgError: 6-th leading minor of the array is not positive definite
</details>

By the way, thanks for taking your time and helping me out! I really, really appreciate it :smile:

**Comment by pablomm** [comment]
Hi!
I've tried to reproduce a similar data set to replicate your problem.

![Figure_1](https://user-images.githubusercontent.com/16774925/60897318-2904f500-a268-11e9-9495-2c86ce96778b.png)

The ``LinAlgError`` error is due to the way of solving the system of equations to calculate the coefficients, by default is used the Cholesky method, more computationally efficient but more unstable. You can pass the parameter ``method='qr'`` to the method ``to_basis`` to avoid this problem.

Due to the spacing of the points this sinusoidal phenomenon appears, even with a large number of bases, it is possible to reduce it by introducing a smoothing parameter, using ``smoothing_parameter`` in the method  ``to_basis`` .

With the following parameters I have obtained the results of the following plot, varying the number of basis

```python
basis = BSpline(domain_range=fd.domain_range[0], nbasis=nbasis)
spline = fd.to_basis(basis=basis, method='qr', smoothness_parameter=15)
```

![Figure_1](https://user-images.githubusercontent.com/16774925/60896809-44233500-a267-11e9-86ca-2d32d0f5bf6b.png)

Try varying these parameters, maybe you can get a better approximation.

You can also try interpolating your values to make them equispaced once you have them in an ``FDataGrid``.
```python
fd = fd.to_grid(sample_points=np.linspace(-500, 3000, 1000))
```
To do this you can also change the default interpolator, to perform cubic interpolation and smooth the data at the same time and then try to convert to basis form

```python
from skfda.representation.interpolation import SplineInterpolator

fd.interpolator = SplineInterpolator(interpolation_order=3, smoothness_parameter=1)
fd = fd.to_grid(sample_points=np.linspace(-500, 3000, 1000))
```
![Figure_1](https://user-images.githubusercontent.com/16774925/60897111-ca3f7b80-a267-11e9-9a24-250bb72f54b2.png)

I hope you find these suggestions helpful.

**Comment by vnmabus** [comment]
@SirWindfield  Please close this issue if you solved your problem

**Comment by SirWindfield** [comment]
Oh ye sure, I actually forgot it :smile: Thank you guys for helping me out!
