### ISSUE TITLE
Problem in fpca

### ISSUE THREAD

**Issue by pablomm** [GAA-UAM/scikit-fda#14]
Second parameter in the function `fpca` is not used. 

https://github.com/GAA-UAM/fda/blob/0b13e96fbf5012dca863ea48a5559cc24d3fbd31/fda/math.py#L408-L432

Maybe the default value of `n` should return all the principal components.

**Comment by pablomm** [comment]
... and don't work either.

> `>>> fda.math.fpca(fdatagrid)`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pablomm/anaconda3/lib/python3.6/site-packages/fda-0.1-py3.6-macosx-10.7-x86_64.egg/fda/math.py", line 294, in fpca
    scores = u @ s  # functional principal scores
ValueError: shapes (15,100,100) and (15,1) not aligned: 100 (dim 2) != 15 (dim 0)

Should be used `u, s, v = numpy.linalg.svd(fdatagrid.data_matrix[..., 0]) ` instead of 
https://github.com/GAA-UAM/fda/blob/0b13e96fbf5012dca863ea48a5559cc24d3fbd31/fda/math.py#L427

**Comment by vnmabus** [comment]
No longer relevant. The function `fpca` was replaced by an `FPCA` estimator in #188.
