### ISSUE TITLE
Unify scalar and functional regressors

### ISSUE THREAD

**Issue by vnmabus** [GAA-UAM/scikit-fda#158]
I was mentioned in a meeting that it makes no sense to differentiate between scalar and functional regressors.  First, because there are not scalar, but multivariate, and second, because there is no confusion: the output of `predict` depends on the input to `fit`.

I forgot to mention this on the review of #112, but it should not be difficult to change. Can you do it @pablomm ?

**Comment by pablomm** [comment]
I can handle it, I forgot to made those changes.
