### ISSUE TITLE
Error while importing skfda

### ISSUE THREAD

**Issue by akashsaha06** [GAA-UAM/scikit-fda#176]
The installation goes through but on importing skfda I run into error ImportError: cannot import name 'OutlierMixin'
![Capture](https://user-images.githubusercontent.com/4928752/70478616-7203f280-1b01-11ea-86cc-c5ebbfd67d90.PNG)

**Comment by vnmabus** [comment]
`OutlierMixin` is in the version 0.20 of sklearn. We should update the setup.py to reflect this dependence.

**Comment by akashsaha06** [comment]
Could you resolve it any soon and let me know?

**Comment by vnmabus** [comment]
You can update scikit-learn in your system yourself by running `pip install --upgrade scikit-learn` (or `conda update scikit-learn` if you are using conda). Adding the dependence to the setup.py is only for performing this action automatically on install.

**Comment by akashsaha06** [comment]
Resolved. Thanks
