### ISSUE TITLE
B spline penalty matrix is wrong

### ISSUE THREAD

**Issue by szhang0629** [GAA-UAM/scikit-fda#185]
**Describe the bug**
0 order B spline penalty matrix should be non-negative since its function values are all negative. However, I get penalty matrix with negative values.

**To Reproduce**
Code to reproduce the behavior:

```python
from skfda.representation.basis import BSpline
bss = BSpline(n_basis=16, order=8)
bss.penalty(0)
```

**Expected behavior**
A non-negative and semi-positive definite matrix

**Version information**
 - OS: Windows
 - Python version: 3.6
 - scikit-fda version: 0.3
 - Version of other packages involved [None ]

**Additional context**

**Comment by vnmabus** [comment]
The error was related to the shifting of the polynomial expresions in B-Splines that was unnecessarily done in the `penalty` method. Thank you for spotting this bug, as it was very subtle!

This error should not happen after PR #189. If you think that the error has not been properly addressed, please reopen this issue. If you find other errors do not hesitate to open a new issue.
