### ISSUE TITLE
ModuleNotFoundError: No module named 'optimum_reparam'

### ISSUE THREAD

**Issue by alejandro-ariza** [GAA-UAM/scikit-fda#196]
Hi, I just forked/cloned the repository and I found a module which is not listed in the dependencies. It's called "optimum_reparam" and it's imported right [here](https://github.com/GAA-UAM/scikit-fda/blob/3def6c2d54ae76e2e32caf9cd3b30d5b13b5eb1a/skfda/preprocessing/registration/elastic.py#L8). Maybe somewhere else. I failed finding the module myself, could someone provide details about this module in the [README](https://github.com/GAA-UAM/scikit-fda/blob/develop/README.rst) requirements section, please?

Thanks for this initiative!

**Comment by vnmabus** [comment]
This is a Cython module in https://github.com/GAA-UAM/scikit-fda/tree/develop/deps/fdasrsf.

Did you have any problems with it?

**Comment by alejandro-ariza** [comment]
I'm getting a `ModuleNotFoundError` when importing optimum_reparam with the Anaconda python distribution (Python 3.7.7, Cython 0.29.15), using Spyder 4.1.2. 
```
import optimum_reparam
>>> ModuleNotFoundError: No module named 'optimum_reparam'
```

I managed to import optimum_reparam with Python 3.6 and Cython 0.29.16 from the terminal, but I do most of my work with Spyder! Anyone knows a workaround to install optimum_reparam with conda?

Thanks.

**Comment by vnmabus** [comment]
Which OS do you use? How have you installed the package?

**Comment by alejandro-ariza** [comment]
Ubuntu 18.04.4 LTS.

I did `pip install scikit-fda` but what I actually need is `conda install scikit-fda`, to use the package from the Anaconda python distribution (Spyder). I found that the later is not available yet so I manually added scikit-fda and all the dependencies in the PYTHONPATH (~/.bashrc). So technically, scikit-fda is not installed in the Anaconda python distribution, I just added the library path.

**Comment by vnmabus** [comment]
Even if you install it from pip, if you do it inside your conda environment it should be available to conda programs. I do not personally use Spyder, but I use Miniconda and never had a problem with that. Did you install from pip while inside your conda environment?

**Comment by alejandro-ariza** [comment]
Sweet, it works!

I had no idea you could "pip install" inside the conda environment, so that's a double win :)

I'm interested in FDA to apply in the field of oceanography. I just forked/cloned the repository to give it a go. Are you fancy guys to receive pull request if I find bugs?

**Comment by vnmabus** [comment]
Yes, of course! Feel free to open PRs and issues or to discuss them.

**Comment by alejandro-ariza** [comment]
Gracias!
