### ISSUE TITLE
Error While Implementing plot_fpca example

### ISSUE THREAD

**Issue by akashsaha06** [GAA-UAM/scikit-fda#206]
After installation skfda is imported. But from 'skfda.preprocessing.dim_reduction.projection import FPCABasis, FPCAGrid' produces error cannot import name 'FPCABasis'. How can this be resolved?

`import numpy as np`
`import skfda`
`from skfda.preprocessing.dim_reduction.projection import FPCABasis, FPCAGrid`
`from skfda.representation.basis import BSpline, Fourier, Monomial`
`from skfda.datasets import fetch_growth`

ImportError                               Traceback (most recent call last)
<ipython-input-2-963952b6c566> in <module>
      4 import numpy as np
      5 import skfda
----> 6 from skfda.preprocessing.dim_reduction.projection import FPCABasis, FPCAGrid
      7 from skfda.representation.basis import BSpline, Fourier, Monomial
      8 from skfda.datasets import fetch_growth

ImportError: cannot import name 'FPCABasis' from 'skfda.preprocessing.dim_reduction.projection' (/opt/anaconda3/envs/pipenv/lib/python3.7/site-packages/skfda/preprocessing/dim_reduction/projection/__init__.py)

**Comment by hzzhyj** [comment]
Hi, how did you install the library? These changed are still in the develop branch. If you want to try this functionality you have to go to the develop branch, clone it, and then in the root library do:
1. python setup.py build
2. python setup.py install

I recommend you use an environment to do this step.

If you used the stable branch, aka installing via pip, then you cannot import this as it is still in develop.

**Comment by akashsaha06** [comment]
Thanks

**Comment by vnmabus** [comment]
Sorry, @akashsaha06, what did you do at the end? Did it solve your problem?

**Comment by akashsaha06** [comment]
Yes it did solve the problem.
