### ISSUE TITLE
FDataGrid.plot has the side effect of printing the plot always in Jupyterlab

### ISSUE THREAD

**Issue by NebulousOinkler** [GAA-UAM/scikit-fda#237]
I am running skfda in Jupyterlab and whenever I call the plot method in FDataGrid, the plot both gets returned and printed, resulting in the same plot showing up twice when I want to see it, and unnecessarily when I'm saving the output to a variable. I'm sure this already has a fix somewhere, and I would greatly appreciate being pointed towards fixing this problem.
My code is quite simple as I'm trying skfda for the first time:

    import skfda as fda
    data = fda.datasets.fetch_weather()
    fd = data['data']
    x, y = fd.coordinates
    output = y.plot()

I expect to return nothing, but it prints the graph of y.

    import skfda as fda
    data = fda.datasets.fetch_weather()
    fd = data['data']
    x, y = fd.coordinates
    y.plot()

I expect one instance of the plot, but I get two.
I'm using Jupyterlab Version 1.2.15 with python 3.7

**Comment by vnmabus** [comment]
This is a problem of how Jupyter and Matplotlib interacts. When a Jupyter cell is executed, Jupyter plots all the Matplotlib plots that are open, even if the user never called `show`. Also, the last expression of a cell is printed, which in the second case is a Matplotlib `Figure`, causing the plot to appear twice.

The following StackOverflow answer explain several fixes:

https://stackoverflow.com/a/62288787/2455333

**Comment by NebulousOinkler** [comment]
Ahhh thank you so much! This is very helpful.
