### ISSUE TITLE
_get_label_colors method created but not used

### ISSUE THREAD

**Issue by mellamansanchez** [GAA-UAM/scikit-fda#318]
Method not used in representation.py

def _get_label_colors(n_labels, group_colors=None):
    """Get the colors of each label"""

    if group_colors is not None:
        if len(group_colors) != n_labels:
            raise ValueError("There must be a color in group_colors "
                             "for each of the labels that appear in "
                             "group.")
    else:
        colormap = matplotlib.cm.get_cmap()
        group_colors = colormap(np.arange(n_labels) / (n_labels - 1))

    return group_colors

**Comment by vnmabus** [comment]
This is already removed in develop.
