### ISSUE TITLE
Deletion of branch feature/refactor-landmark

### ISSUE THREAD

**Issue by pablomm** [GAA-UAM/scikit-fda#337]
The branch `feature/refactor-landmark` is abandoned and outdated, can be deleted. If the landmark registration code is refactored it makes more sense to continue from a current version of the package.

**Comment by vnmabus** [comment]
In fact that refactor is stalled until some issues in scikit-learn are solved, as explained in #229. I will delete the branch.

**Comment by vnmabus** [comment]
Branch deleted.
