### ISSUE TITLE
Deepcopy of FDataBasis object

### ISSUE THREAD

**Issue by manso92** [GAA-UAM/scikit-fda#34]
Shouldn't it make a copy of the coefficients too?

https://github.com/GAA-UAM/fda/blob/92c984cb42a505661716c26f4cd56a2f1e69e26f/fda/basis.py#L1762-L1763

**Comment by vnmabus** [comment]
Pablo and I talked about making the coefficients read-only (but it is not implemented). In that case, sharing should not be a problem.
