### ISSUE TITLE
ImportError: cannot import name 'AgglomerativeClustering'

### ISSUE THREAD

**Issue by Librajiayou** [GAA-UAM/scikit-fda#341]
**Describe the bug**
When importing functions from 'skfda.ml.clustering', I get an import error:

ImportError: cannot import name 'AgglomerativeClustering'

I have downloaded the package with

pip install scikit-fda
and I was trying to follow the documentation, but I get errors on the import statements

**To Reproduce**
Code to reproduce the behavior:

```python
import skfda
from skfda.ml.clustering import AgglomerativeClustering
...

```

**Expected behavior**
I am expecting the import statements to work as in the documentation

**Version information**
 - OS: Ubuntu
 - Python version: 3.6.9
 - scikit-fda version: 0.5

**Additional context**

**Comment by vnmabus** [comment]
The documentation by default refers to the `latest` (`develop`) branch. Thus it can contain things not yet released in a stable version, such as `AgglomerativeClustering`. If you need the documentation for the latest stable branch (`master`) it is also available in ReadTheDocs.

If you need that functionality before it is officially released, you can also install and use the development version: 
```python
pip install git+https://github.com/GAA-UAM/scikit-fda.git@develop
```

**Comment by Librajiayou** [comment]
Yes, it did work. I successfully use the function. Thank you very much!
