### ISSUE TITLE
What is the proper data preprocessing before using FPCA?

### ISSUE THREAD

**Issue by hovinh** [GAA-UAM/scikit-fda#368]
Hi scikit-fda team,

I have a time-series dataset with 50 traces and approximate 330 data points per trace. 
![image](https://user-images.githubusercontent.com/7614509/137440073-10ba11cb-6732-4337-86a5-7c49d60c3fd1.png)

The mean trace looks like this:
![image](https://user-images.githubusercontent.com/7614509/137440316-90713ca7-2cd0-41bf-8e8f-dfce8f44e5ff.png)

I would like to apply FPCA on them and later use PC score for a classification task. There are 2 ways I tried out:
- Method 1: apply FPCA directly on the traces in discrete form. 
![image](https://user-images.githubusercontent.com/7614509/137446467-c4431f89-46f9-43fb-9378-9b25f40c5736.png)
Top 5 components' explained variance ratio are: `[0.41167929 0.14467096 0.08427026 0.04618083 0.03430349]`

- Method 2: use Elastic Registration to remove phase variation in prior to apply FPCA. 

`Elastic Registration`:
![image](https://user-images.githubusercontent.com/7614509/137446673-c5620e50-ceed-47d7-b6ec-b256418f8db7.png)

`FPCA`:
![image](https://user-images.githubusercontent.com/7614509/137446277-922480a8-8e1d-480d-9dbf-8da40cd843cd.png)
Top 5 components' explained variance ratio are: `[0.11482679 0.10225417 0.09011544 0.08024505 0.06961226]`

Given the above observation, I have the following question:
- Is it true if I conclude `Elastic Registration` is not a good way to preprocess data in prior to feed into FPCA, based on the  explained variance ratio? Do you know why it is so?

In one of your example, FPCA can be done on either discrete form or functional form. Therefore, I tried out the same experiment with basis found in issue #367 (`BSpline, n_basis=200`) and obtained similar result in explained variance ratio, with and without registration, so this seems data form is irrelevant. Do you have any suggestion on proper way to preprocess my data before feeding in FPCA?

Thank you. 

Sincerely,
Vinh

**Comment by vnmabus** [comment]
As this is not an issue of the package, but instead a usage question, I am moving it to Discussions.

Your data is very atypical for Functional Data Analysis. Usually data in FDA is continuous and may take a continuum of values, while your data seems to take only two values (as far as I can see, the jump from one to the other is instantaneous, between measures). My first approach would be to use multivariate tools encoding each signal as a sequence of ones and zeros. Alternatively if you know that the data has always the same number of peaks you can "compress" your data as a vector of positions and durations of the peaks.

If you really like to use functional tools, for example for alignment, I would use the discretized representation or maybe a wavelet basis, such as the [haar basis](https://en.wikipedia.org/wiki/Haar_wavelet). This basis is not currently implemented, but you can add custom bases easily by just subclassing the [Basis class](https://fda.readthedocs.io/en/latest/modules/autosummary/skfda.representation.basis.Basis.html) and implementing the `_evaluate` method (see for example how it is done in Monomial).
