### ISSUE TITLE
update citation for elastic registration

### ISSUE THREAD

**Issue by ll-portes** [GAA-UAM/scikit-fda#385]
Hi guys. It is not a "bug" in the code and I don't know if posting here is the correct way to report it. Sorry if this is the wrong communication channel. 

In the example for Elastic registration, the main citation has **inverted** the book title and chapter. In the current version at (https://fda.readthedocs.io/en/stable/auto_examples/plot_elastic_registration.html it is:

- Srivastava, Anuj & Klassen, Eric P. (2016). Functional and shape data analysis. In Functional Data and Elastic Registration (pp. 73-122). Springer.

However, it should be (as at Springer webpage https://link.springer.com/chapter/10.1007/978-1-4939-4020-2_4#citeas):

- Srivastava A., Klassen E.P. (2016) Functional Data and Elastic Registration. In: Functional and Shape Data Analysis. Springer Series in Statistics. Springer, New York, NY.

**Comment by vnmabus** [comment]
A bug in the documentation is still a bug, so this is the appropriate channel. Thank you for the bug report!

**Comment by vnmabus** [comment]
Fixed in 1b3716b8e04149c0721615a712d641290ae5c982. Thank you again for reporting this!
