### ISSUE TITLE
Error when calling L2Regularization

### ISSUE THREAD

**Issue by dcbrien** [GAA-UAM/scikit-fda#413]
I have tried different python versions, but calling:

`regularization=L2Regularization(LinearDifferentialOperator())`

As in the docs, results in the following error:

**TypeError: __init__() takes 1 positional argument but 2 were given**

**Comment by vnmabus** [comment]
Sorry, you are looking at the docs of the development version, where this have been changed recently. You can either use the development version, or use `TikhonovRegularization` in older versions instead.

**Comment by dcbrien** [comment]
Thank you for the update. I will try those.

**Comment by vnmabus** [comment]
BTW, the latest version released yesterday should match the documentation. Tell me when you try, to close the issue.

**Comment by dcbrien** [comment]
Thank you. I am using the development version and have had no more issues. I successfully integrated these tools into a custom sklearn pipeline. Thank you for this library.

**Comment by vnmabus** [comment]
Thank you! Don't hesitate to open another issue if you have further problems.
