### ISSUE TITLE
Error on importing FPCA

### ISSUE THREAD

**Issue by SkyJoyTianle** [GAA-UAM/scikit-fda#448]
**Describe the bug**
ImportError                               Traceback (most recent call last)
/var/folders/b7/znhy5tqn62g96g4j4cdtxvs00000gn/T/ipykernel_5617/2223815277.py in <module>
      4 from skfda.datasets import fetch_growth
      5 from skfda.exploratory.visualization import FPCAPlot
----> 6 from skfda.preprocessing.dim_reduction import FPCA
      7 from skfda.representation.basis import BSpline, Fourier, Monomial

ImportError: cannot import name 'FPCA' from 'skfda.preprocessing.dim_reduction' (/opt/anaconda3/lib/python3.9/site-packages/skfda/preprocessing/dim_reduction/__init__.py).

**To Reproduce**
Code to reproduce the behavior:

```python
import skfda
from skfda.preprocessing.dim_reduction import FPCA
...

```

**Expected behavior**
A clear and concise description of what you expected to happen, results or figures.

**Version information**
 - OS: MacOs Monterey 12.3.1
 - Python version: 3.9
 - scikit-fda version: 0.7.1
 - Version of other packages involved [e.g. numpy, scipy, matplotlib, ... ]

**Additional context**
I am trying the example of FPCA in the document, but I can't import the FPCA on my MacOS or the Google Colab, could you tell me why and how to solve it?

**Comment by SkyJoyTianle** [comment]
I just change the import code as from skfda.preprocessing.dim_reduction.feature_extraction import FPCA.
It is because that the FPCA class is in the package feature_extraction not the dim_reduction directly

**Comment by vnmabus** [comment]
Yes. You are looking at the `latest` version of the documentation, which correspond to the `development` branch. You can instead read the documentation for the `stable` version, that correspond to the `master` branch.

We have changed the location of `FPCA` in the development branch. In the master branch (the one released) you can import it as:
```python
from skfda.preprocessing.dim_reduction.feature_extraction import FPCA
```

This will still work for the next couple of releases (but with a warning). The new way to import it, starting from the next release, is:
```python
from skfda.preprocessing.dim_reduction import FPCA
```

Sorry for the confusion. As we are adding more features to the library sometimes we have to rethink the ways things were previously done, and with two versions of the docs it can be a little bit confusing.

**Comment by SkyJoyTianle** [comment]
Thanks for your quick reply. I am okay with this problem.
