### ISSUE TITLE
FPCA import statement in gallery example

### ISSUE THREAD

**Issue by fabian-sp** [GAA-UAM/scikit-fda#468]
Hi,

this is rather an FYI than a real issue, but in your example 

https://fda.readthedocs.io/en/latest/auto_examples/plot_fpca_inverse_transform_outl_detection.html#sphx-glr-auto-examples-plot-fpca-inverse-transform-outl-detection-py

the import of `FPCA` , i.e.

`from skfda.preprocessing.dim_reduction import FPCA`

does not work with the current version from `pip` ( have version `0.7.1` installed). I had to run 

`from skfda.preprocessing.dim_reduction.feature_extraction import FPCA`

instead. But the package is great to use and awesomely documented, thanks you!

Cheers,
Fabian

**Comment by vnmabus** [comment]
This is similar to #448. You are looking at the "latest" documentation, that contains changes not yet released in PyPI, only available in the `develop` branch. You can look at the "stable" version for the last uploaded version.

That said, I plan to do a release in a few weeks, so the stable documentation will be updated accordingly.

**Comment by vnmabus** [comment]
BTW, thank you for reporting it anyway, rereading my comment it sounds a bit dry 😅.
