### ISSUE TITLE
Rename Gramian matrix to Gram matrix.

### ISSUE THREAD

**Issue by vnmabus** [GAA-UAM/scikit-fda#501]
In some places we use the terminology Gramian matrix (even in function names). We should use always the name Gram matrix for consistency.

**Comment by Saumya-ranjan** [comment]
I'd like to take this up. I would really appreciate some clarification on the same

**Comment by vnmabus** [comment]
Sure! There are some places in which we used the terminology "Gramian matrix" instead of the more common "Gram matrix":
https://github.com/GAA-UAM/scikit-fda/search?q=gramian

In particular, the functions `gramian_matrix`, `gramian_matrix_numerical` and `gramian_matrix_optimization` should be renamed, as well as the related comments. As far as I know, nobody is using these functions in other projects (although `gramian_matrix_optimization` was exposed to be able to provide optimized implementations for particular combinations of basis and operator), so no deprecation would be needed.

I assign you to this issue, please tell me in case you have any other doubt.

**Comment by Saumya-ranjan** [comment]
So Basically we have to change Gramian_matrix,gramian_matrix_numerical to Gram matrix to be more consistent. Wherein gramian _matrix_optimization is able to provide optimized implementation so it doesn't need to be changed right?

**Comment by vnmabus** [comment]
All of them should be renamed. The search for gramian should return 0 results.

**Comment by Saumya-ranjan** [comment]
@vnmabus please do review this if it's how to do it https://github.com/GAA-UAM/scikit-fda/pull/502

**Comment by vnmabus** [comment]
Solved in #502.
