### ISSUE TITLE
incomplete package

### ISSUE THREAD

**Issue by dlunah** [GAA-UAM/scikit-fda#525]
Hi, I downloaded and installed the scikit-fda package, can import it, but it seems to be missing some of the functions that are documented.  For example the documentation (https://fda.readthedocs.io/en/latest/modules/ml/autosummary/skfda.ml.regression.FPCARegression.html) talks about the FPCARegression method, but when trying to follow the example I can't load such method, getting the error message:

`ImportError: cannot import name 'FPCARegression' from 'skfda.ml.regression' (C:\Users\diieg\Anaconda3\lib\site-packages\skfda\ml\regression\__init__.py)`

After checking for the method, I found this:

```
print(dir(skfda.ml.regression))
['HistoricalLinearRegression', 'KNeighborsRegressor', 'LinearRegression', 'RadiusNeighborsRegressor', '__builtins__', 
'__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_coefficients', 
'_historical_linear_model', '_linear_regression', '_neighbors_regression']
```

So it looks like the method FPCARegression was not downloaded/installed?

I'm running python version Python 3.7.6 in anaconda

Also, when trying to load FPCA I couldn't do it, it looks like it is in a different place.  From the documentation it should be at 
`skfda.preprocessing.dim_reduction.FPCA` but it is at  `skfda.preprocessing.dim_reduction.feature_extraction.FPCA`

Thank you

**Comment by vnmabus** [comment]
The documentation you are using correspond to the development version (it has "latest" in the url). Thus, some recent changes are still not available in the released version.

You can search the documentation of the currently released version by replacing "latest" in the url by "stable": https://fda.readthedocs.io/en/stable/index.html. We probably should made that more clear in the docs.

If you need functionality that has not been released yet, you can [install it from source](https://github.com/GAA-UAM/scikit-fda#installation-from-source) or tell pip that install it from the git repo directly as:

```bash
pip install git+https://github.com/GAA-UAM/scikit-fda.git@develop
```

**Comment by dlunah** [comment]
Thank you!
