### ISSUE TITLE
SRSF doc wrong formula

### ISSUE THREAD

**Issue by ego-thales** [GAA-UAM/scikit-fda#530]
Hello,

I just wanted to point out that the [SRSF doc](https://fda.readthedocs.io/en/latest/modules/misc/autosummary/skfda.misc.operators.SRSF.html) defines
$$SRSF(f) := \text{sign}(f)\sqrt{\vert f'\vert},$$
instead of (notice the derivative in the sign function)
$$SRSF(f) := \text{sign}(f')\sqrt{\vert f'\vert}.$$

Cheers

**Comment by ego-thales** [comment]
_Edited the issue since the code isn't bugged as I thought it might be at first glance._

**Comment by vnmabus** [comment]
Thank you for reporting it! Do you want to provide a fix?

**Comment by ego-thales** [comment]
Ok I will, but probably later next week :+1:

**Comment by vnmabus** [comment]
Solved in #542.
