### ISSUE TITLE
DTMClassifier citation is wrong.

### ISSUE THREAD

**Issue by vnmabus** [GAA-UAM/scikit-fda#535]
**Describe the bug**
The citation in the documentation page of the method DTMClassifier is wrong, as it refers to the trimmed mean, and not to the DTM method itself.
The DTM method appeared originally in the following reference, which should appear instead:
```bibtex
@incollection{pintado+romo_2005_depthbased,
  title = {Depth-Based Classification for Functional Data},
  shorttitle = {Data {{Depth}}},
  booktitle = {Data {{Depth}}: {{Robust Multivariate Analysis}}, {{Computational Geometry}} and {{Applications}}},
  author = {Pintado, Sara and Romo, Juan},
  year = {2005},
  month = nov,
  series = {{{DIMACS Series}} in {{Discrete Mathematics}} and {{Theoretical Computer Science}}},
  volume = {72},
  pages = {103--119},
  publisher = {{American Mathematical Society}},
  doi = {10.1090/dimacs/072/08},
  isbn = {978-0-8218-3596-8}
}
```

**Comment by Unessam** [comment]
@vnmabus are you referring to this page? 
https://fda.readthedocs.io/en/latest/modules/ml/autosummary/skfda.ml.classification.DTMClassifier.html#skfda.ml.classification.DTMClassifier
I believe keeping the current reference and adding the suggested one would be better as both are discussed here, please let me know your thoughts.

**Comment by vnmabus** [comment]
Yes, it is that page. If we keep the reference to the trimmed means, that footnote should be moved to  make clear that it only refers to that concept.

We should probably also include a reference to `trim_mean` in the "See also" section.
