### ISSUE TITLE
discontinuity in registration

### ISSUE THREAD

**Issue by mrrezaie** [GAA-UAM/scikit-fda#545]
Hi, I'm looking for a function to register the curves only horizontally. In [Shift Registration](https://fda.readthedocs.io/en/stable/auto_examples/plot_shift_registration.html) example, the starting and ending points of the curves are also registered vertically. 
<img src="https://fda.readthedocs.io/en/stable/_images/sphx_glr_plot_shift_registration_002.png" width=40% height=40%> <img src="https://fda.readthedocs.io/en/stable/_images/sphx_glr_plot_shift_registration_003.png" width=40% height=40%> 
I tried [Elastic registration](https://fda.readthedocs.io/en/stable/auto_examples/plot_elastic_registration.html) example but it leads to discontinuities in my curves:

<img src="https://github.com/GAA-UAM/scikit-fda/assets/38867713/b37a9928-c6c9-4e4c-a69f-7858935ac99b" width=40% height=40%> <img src="https://github.com/GAA-UAM/scikit-fda/assets/38867713/7a88b8ff-c9fc-400b-be47-416ac9639812" width=40% height=37%> 

Any idea how to improve it? Any help is greatly appreciated. 
-Mohammadreza

**Comment by mrrezaie** [comment]
Increasing the penalty parameter improved the curves.

**Comment by vnmabus** [comment]
Sorry for not answering before. Indeed, using the penalty parameter should penalize rough transformations and thus improve the curves.

**Comment by mrrezaie** [comment]
@vnmabus Thank you so much for your response.
