### ISSUE TITLE
Example of `scipy.interpolate.BSpline.design_matrix` equivalent with`skfda.representation.basis.BSplineBasis`

### ISSUE THREAD

**Issue by avivajpeyi** [GAA-UAM/scikit-fda#558]
Hey all, 

I've been trying to migrate from scipy's b-splines to skfda's b-splines. During this process, I've made several testing scripts to ensure that Im changing things appropriately. 

Here is a small demo script that generates a `BSpline.design_matrix` with `scipy` and `skfda`. 

```python
import numpy as np
from skfda.representation.basis import BSplineBasis
from scipy.interpolate import BSpline as scipy_BSpline
import matplotlib.pyplot as plt

degree = 3
knots = np.linspace(0, 1, 5)
knots_with_boundary = np.r_[[knots[0]] * degree, knots, [knots[-1]] * degree]
x = np.linspace(0, 1, 50)

scipy_matrix = scipy_BSpline.design_matrix(x, knots_with_boundary, degree).toarray()
# no need to add boundary knots (they are added automatically)
fda_basis = BSplineBasis(knots=knots, order=degree + 1)
fda_matrix = fda_basis.to_basis().to_grid(grid_points=x).data_matrix.squeeze()

# plot of basis functions
fig, ax = plt.subplots(1, 3, figsize=(12, 3))
ax[0].set_title('Basis functions')
for i, db in enumerate(scipy_matrix.T):
    ax[0].plot(db, color=f"C{i}", alpha=0.3, lw=2)
for i, d in enumerate(fda_matrix):
    ax[0].plot(d, color=f"C{i}", alpha=0.6, ls='--')
handles = [plt.Line2D([0], [0], color="gray", alpha=0.3, lw=2),
           plt.Line2D([0], [0], color="gray", alpha=0.6, lw=1, ls='--'), ]
labels = ['SCIPY', 'FDA']
ax[0].legend(handles, labels, loc='upper right')

ax[1].pcolor(scipy_matrix)
ax[1].set_title('SCIPY B-spline matrix')
ax[1].set_xlabel('Basis function')

ax[2].pcolor(fda_matrix.T)
ax[2].set_title('FDA B-spline matrix')
ax[2].set_xlabel('Basis function')
plt.tight_layout()
plt.show()

```

The associated plot:
![bspline_basis_design_matrix](https://github.com/GAA-UAM/scikit-fda/assets/15642823/c24bc10f-b0cf-4810-8e64-d2af1d6d8942)

Do you think something like this demo script would be helpful to other users (in the documentation)? I'd be happy to help clean this up, and make a PR.

**Comment by vnmabus** [comment]
The `BSplineBasis` object in scikit-fda is not intended to be a replacement of SciPy's B-splines (in fact, they are used internally). This object is just used to define a particular basis of functions for a `FDataBasis` object. Although some procedures, such as the computation of the design matrix, can be done with both, there exist some differences and I am not sure if I would recommend using scikit-fda for that purpose. First, as SciPy's B-splines are used internally, the scikit-fda implementation can only be slower. Secondly, the implementation of `design_matrix` in SciPy returns a sparse matrix, which will be more efficient in both memory and speed for a high number of basis elements.

Thus, unless you can provide a better explanation of why that should be done, I do not think that this is useful for most users.

Finally, note that there is an easier and faster way to compute that design matrix in scikit-fda:
```python
fda_matrix = fda_basis(x)[..., 0]
```

**Comment by avivajpeyi** [comment]
Ah I see! Thanks @vnmabus. In that case maybe we can close this issue.

Tbh the main reason I am using scikit-fda now instead of scipy' Bsplines is because I need to generate a penalty matrix for my basis (which I didn't know how to do with scipy's Bsplines, but can do with scikit-fda) 


This might be another issue, but since the scipy design matrix is more efficient, is it possible to generate a penalty matrix for that via the scikit-fda interface?

**Comment by vnmabus** [comment]
Unfortunately no. However for a small number of basis elements the difference in performance is probably not that much.

I will close this issue as not planned, then.
