### ISSUE TITLE
Errors in test_pandas_*.py setups with pandas==2.1.0

### ISSUE THREAD

**Issue by pcuestas** [GAA-UAM/scikit-fda#570]
**Describe the problem**
The setups of some tests from test_pandas_fdatabasis.py and test_pandas_fdatagrid.py are throwing an error since 2.1.0 pandas version (released Aug 30, 2023). 

**To Reproduce**
Execute previously mentioned tests with 2.1.0 version of pandas.

**Expected behavior**
Tests should be passing without errors. (This is the behavior that I get when executing the tests having pandas==2.0.3).

**Actual behavior**
Test ouput (one of the errors -- the rest are almost identical):
```
_ ERROR at setup of TestNumericReduce.test_reduce_series_boolean[basis0-True] __
file /opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/pandas/tests/extension/base/reduce.py, line 79
      @pytest.mark.parametrize("skipna", [True, False])
      def test_reduce_series_boolean(self, data, all_boolean_reductions, skipna):
E       fixture 'all_boolean_reductions' not found
>       available fixtures: all_arithmetic_operators, all_compare_operators, all_data, all_numeric_reductions, as_array, as_frame, as_series, basis, box_in_series, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, data, data_for_grouping, data_for_sorting, data_for_twos, data_missing, data_missing_for_sorting, data_repeated, doctest_namespace, dtype, fillna_method, groupby_apply_op, monkeypatch, na_cmp, na_value, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, subtests, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, use_numpy
>       use 'pytest --fixtures [testpath]' for help on them.
```

**Version information**
 - OS: ubuntu-latest
 - Python version: 3.9
 - scikit-fda version: develop
 - Version of other packages involved: `pandas==2.1.0`

**Comment by vnmabus** [comment]
Fixed in #572.
