### ISSUE TITLE
Warning fetching tecator

### ISSUE THREAD

**Issue by pablomm** [GAA-UAM/scikit-fda#62]
A warning is generated when `fetch_tecator` is called.
> fda.datasets.fetch_tecator()
Using TensorFlow backend.
/Users/pablomm/anaconda3/lib/python3.6/site-packages/rdata-0.2.1-py3.6.egg/rdata/conversion/_conversion.py:197: UserWarning: Unknown encoding. Assumed ASCII.
  warnings.warn(f"Unknown encoding. Assumed ASCII.")

**Comment by vnmabus** [comment]
Fixed in 7af8449945c595cad9f7ad5fa6402ea21a03274c.
